// Canadian Bank Institution Numbers and Names
export const CANADIAN_BANKS = {
  '001': 'Bank of Montreal',
  '002': 'Bank of Nova Scotia (Scotiabank)',
  '003': 'Royal Bank of Canada',
  '004': 'Toronto-Dominion Bank',
  '006': 'National Bank of Canada',
  '010': 'Canadian Imperial Bank of Commerce',
  '016': 'HSBC Bank Canada',
  '030': 'Canadian Western Bank',
  '039': 'Laurentian Bank of Canada',
  '117': 'Government of Canada',
  '127': 'Canada Post Corporation',
  '177': 'Desjardins Bank',
  '219': 'ATB Financial',
  '260': 'Citibank Canada',
  '269': 'American Express Bank of Canada',
  '270': 'JPMorgan Chase Bank',
  '290': 'UBS Bank (Canada)',
  '308': 'Bank of China (Canada)',
  '309': 'Citizens Bank of Canada',
  '326': "President's Choice Financial",
  '338': 'Canadian Tire Bank',
  '340': 'ICICI Bank Canada',
  '509': 'Canada Trust Company',
  '540': 'Manulife Bank of Canada',
  '614': 'Tangerine Bank',
  '621': 'Servus Credit Union',
  '809': 'Central 1 Credit Union',
  '815': 'Caisses Desjardins du Québec',
  '828': 'Central Alberta Credit Union',
  '829': 'Conexus Credit Union',
  '837': 'Meridian Credit Union',
  '865': 'Coastal Capital Savings',
  '879': 'Développement international Desjardins',
  '889': 'Caisse centrale Desjardins',
};
